# Generated by Django 5.2.4 on 2025-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaceAssignment",
            fields=[
                (
                    "face_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("frame_number", models.IntegerField()),
                ("chunk_number", models.IntegerField()),
                ("timestamp", models.CharField(max_length=20)),
                ("confidence", models.FloatField()),
                (
                    "thumbnail_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("bbox_x1", models.IntegerField()),
                ("bbox_y1", models.IntegerField()),
                ("bbox_x2", models.IntegerField()),
                ("bbox_y2", models.IntegerField()),
            ],
            options={
                "db_table": "face_assignments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FaceCluster",
            fields=[
                ("cluster_id", models.AutoField(primary_key=True, serialize=False)),
                ("representative_embedding", models.BinaryField()),
                ("face_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "face_clusters",
                "ordering": ["-face_count"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
                "managed": False,
            },
        ),
    ]
